# Dockerfile.api
# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /apidir


RUN mkdir -p /audio /download /img /json /log /uploads

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*


COPY . .

# CMD ["python", "aiapi/run_api.py"]


#### CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "80"] ####, "--log-level=critical"]
#### CMD ["python", "app/run_api.py"]

