FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

ENV PYTHONUNBUFFERED=1

WORKDIR /

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y apt-utils \
    postgresql \
    postgresql-contrib \
    postgresql-client 

COPY . .


CMD ["uvicorn", "app.api:app", "--host=0.0.0.0", "--port=80"]

#"--log-level", "critical"
#CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "80"]
#"--log-level=critical"
