# Dockerfile.api-bot
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /apibotdir

RUN mkdir -p /audio /download /img /json /log /uploads /backup_db

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["python", "aiapi/bot.py"]