"""Initial migration

Revision ID: 198204e75f86
Revises: 
Create Date: 2024-09-18 01:06:54.058637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198204e75f86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('appkey', sa.UUID(), nullable=False),
    sa.Column('is_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_block', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('date_block', sa.DateTime(), nullable=True),
    sa.Column('date_last_activ', sa.DateTime(), nullable=True),
    sa.Column('money', sa.Float(), server_default='0', nullable=False),
    sa.Column('money_currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_appkey'), 'users', ['appkey'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_is_block'), 'users', ['is_block'], unique=False)
    op.create_index(op.f('ix_users_is_failed'), 'users', ['is_failed'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('use_model', sa.String(length=100), nullable=False),
    sa.Column('sesion_token', sa.Float(), server_default='0', nullable=False),
    sa.Column('price_1_tok', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_price', sa.Float(), server_default='0', nullable=False),
    sa.Column('username_table_stat', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['username_table_stat'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_username_table_stat'), 'statistics', ['username_table_stat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_username_table_stat'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_failed'), table_name='users')
    op.drop_index(op.f('ix_users_is_block'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_appkey'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
