"""Initial migration

Revision ID: d0565499c551
Revises: 
Create Date: 2024-08-30 17:30:28.896435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0565499c551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('date_changes', sa.DateTime(), nullable=True),
    sa.Column('task', sa.String(length=1000), nullable=True),
    sa.Column('is_complite', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('counter', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('appkey', sa.UUID(), nullable=False),
    sa.Column('is_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_block', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('date_block', sa.DateTime(), nullable=True),
    sa.Column('money', sa.Float(), server_default='0', nullable=False),
    sa.Column('money_currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('use_model', sa.String(length=50), nullable=False),
    sa.Column('sesion_token', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price_1_tok', sa.Float(), server_default='0', nullable=False),
    sa.Column('price_sesion_tok', sa.Float(), server_default='0', nullable=False),
    sa.Column('users_telegram_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['users_telegram_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_users_telegram_id'), 'statistics', ['users_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_users_telegram_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('exchange')
    op.drop_table('backup')
    # ### end Alembic commands ###
